apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-xvbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-xvbe
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-xvbe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-xvbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-xvbe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-szpe-tenant/nodejs-users/simple-nodejs-app-xvbe@sha256:840daedb917780f575e6123b67d54672cd197c0b70b72b35519b7393f878f0ec
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
